# Generated by Django 6.0.2 on 2026-03-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_transferred',
            field=models.BooleanField(default=False),
        ),
    ]
