# Generated by Django 6.0.2 on 2026-03-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_order_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transferred_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
