# Generated by Django 6.0.2 on 2026-03-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_order_transferred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='packing_photo',
            field=models.ImageField(blank=True, null=True, upload_to='packing_photos/'),
        ),
    ]
