# Generated by Django 6.0.2 on 2026-03-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_restockorder_status_supplier_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.TextField(blank=True, help_text='Store Pickup Address for Delivery Agents', null=True),
        ),
    ]
