# Generated by Django 6.0.2 on 2026-03-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_store_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='batch_id',
            field=models.CharField(blank=True, help_text='Groups multi-store orders from a single checkout', max_length=100, null=True),
        ),
    ]
